# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Tqoq4-aiFTtzpfxCUJs06s1dteDRbmK
"""

## DB CONNECTION
## data source: https://www.kaggle.com/datasets/kendallgillies/nflstatistics/data

!pip install sqlalchemy pymysql pandas

import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv('Basic_Stats.csv')
df

username = 'alicia'
password = '*****'
hostname = '*****'
database = ''

connection_string = f'mysql+pymysql://{alicia}:{***}}@{hostname}/{database}'

engine = create_engine(connection_string)

df.to_sql('player_stats', engine, if_exists='replace')

query = '''
select *
from player_stats
where College like 'Notre Dame';
'''

test_return = pd.read_sql(query, engine)
test_return